from excercise import Excercise

if __name__ == "__main__":
    calculate_instance = Excercise()
    print('Ejemplos con parametros: -o=hd 4')
    calculate_instance.fibonacci('-o=hd 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=vd 4')
    calculate_instance.fibonacci('-o=vd 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=vi 4')
    calculate_instance.fibonacci('-o=vi 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=hi 4')
    calculate_instance.fibonacci('-o=hi 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=hi -f=salida.txt 4')
    calculate_instance.fibonacci('-o=hi -f=salida.txt 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=hi -m=s 4')
    calculate_instance.fibonacci('-o=hi -m=s 4')
    print('-------------------------------')
    print('Ejemplos con parametros: -o=hi -f=salida.txt -m=s 4')
    calculate_instance.fibonacci('-o=hi -f=salida.txt -m=s 4')